Added octave-forge-jhandles-0.3.4.
The test still doesn't work because jogl seems to be broken:
 java.lang.UnsatisfiedLinkError: no gluegen-rt in java.library.path